version: '3.6'
services:
  dev:
    image: arturictus/plutus-pioneer-program:week06-cabal
    volumes:
      - ./:/app
    command:
      - '/bin/bash'
  server:
    image: arturictus/plutus-pioneer-program:week06-playground
    ports:
      - '8080:8080'
    command:
      - nix-shell
      - --run
      - 'cd plutus-playground-client && plutus-playground-server'
  client:
    image: arturictus/plutus-pioneer-program:week06-playground
    command:
      - nix-shell
      - --run
      - 'cd plutus-playground-client && npm run start'
    depends_on:
      - server
    ports:
      - '8009:8009'
    links:
      - server
  nix-shell:
    build:
      context: .
      dockerfile: Dockerfile-nix-cabal
    # image: arturictus/plutus-pioneer-program:week06-playground
    command:
      - nix-shell
    volumes:
      - ./:/app
