version: '3.6'
services:
  dev:
    image: arturictus/plutus-pioneer-program:week03
    volumes:
      - ./:/app
    command:
      - '/bin/bash'
  server:
    image: arturictus/ppp:0.0.3
    ports:
      - '8080:8080'
    command:
      - nix-shell
      - --run
      - 'cd plutus-playground-client && plutus-playground-server'
  client:
    image: arturictus/ppp:0.0.3
    command:
      - nix-shell
      - --run
      - 'cd plutus-playground-client && npm run start'
    depends_on:
      - server
    ports:
      - '8009:8009'
    links:
      - server
